meta_product_name: "FlashWine"
meta_title: "FlashWine - Learn, taste and share"
meta_description: "Apprends, goute et partage. Découvre le vin en t'amusant et partage avec tes amis tes plus belles bouteilles."
meta_image: "friends-unsplash.png" # should exist in `app/assets/images/`
